### ISSUE TITLE
Discussion: Decide on a filter

### ISSUE THREAD

**Issue by pool011** [pool011/Assignment-Base#1]
What item should our form be filtering for?

**Comment by ColinMannix** [comment]
The filtering priority should be on the restaurant's name.
City and category could also be valid as secondary.

**Comment by pool011** [comment]
I like this. If we can, we should include all three.

**Comment by pool011** [comment]
@daitch-umd what are your thoughts?

**Comment by daitch-umd** [comment]
I think name of the restaurant makes the most sense.
