### ISSUE TITLE
Remove duplicates from list returns

### ISSUE THREAD

**Issue by pool011** [pool011/Assignment-Base#2]
API branch: The algorithm for filtering matches is selecting duplicates. Appears to be happening if the input of the search bar matches more than one category.

**Comment by ColinMannix** [comment]
We'll have to add code that only selects once, probably by selecting unique IDs

**Comment by ColinMannix** [comment]
I think we should tackle that with a findMatches function like he does in the yt video

**Comment by ColinMannix** [comment]
Got way ahead of myself there, we already have one

**Comment by pool011** [comment]
I just have to modify it to fix it. Fork a new branch if you want to try and fix it.
